version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns: 127.0.0.1
    ports:
      - "10.6.0.1:53:53/tcp"
      - "10.6.0.1:53:53/udp"
      - "10.6.0.1:8082:80"
      - "10.6.0.1:67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "10.6.0.1:4043:443"
    networks:
      - default
    environment:
      DNS1: 172.18.0.2#53
      DNS2: 0.0.0.0
      TZ: "Etc/UTC"
      PROXY_LOCATION: pihole
      DNSMASQ_LISTENING: single
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # Required if you are using Pi-hole as your DHCP server, else not needed
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  default:
    name: pi-net
    external: true
